### ISSUE TITLE
Installation step in your README

### ISSUE THREAD

**Issue by ShadowXBoss696** [ankan-das-2001/Classroom-Attendance-System#1]
Hi Devs,
One thing I found in your README file which doesn't really go with the project is that in your README you mentioned in the [installation step](https://github.com/ankan-das-2001/Classroom-Attendance-System#installation) the following line -
```
pip install #name
```

For any python project to be installed from **[PyPI](https://pypi.org/)** repository, you need to follow some conventions like inclusion of `setup.py` file, etc. but your project does not go with such conventions ...

I do believe that you have planned to release the project at PyPI in near future ... So it's my suggestion to either follow the conventions during the design phase of the work or make a proper explanation of your installation procedure or usage in the README file.

Hoping, to see the completion of the project ...

Thanking You,
@Edumate696 

Useful Reference: [How to upload your python package to PyPi - Medium](https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56)

**Comment by tapati-chakraborty** [comment]
issue resolved
